### ISSUE TITLE
TypeError: Cannot read property 'apiKey' of undefined

### ISSUE THREAD

**Issue by dbounds** [aullman/OpenTok-Angular#10]
Hi @aullman,

I'm getting a undefined error on the following line during my call to OTSession.init(): https://github.com/aullman/OpenTok-Angular/blob/master/opentok-angular.js#L101

At this time the OTSession referenced on that line looks like:

{"streams":[],"connections":[],"publishers":[]}

I've verified the API key, session and token are being provided properly to init(), in fact at the present time the API key is a static value being passed to init().

**Comment by aullman** [comment]
I should probably update that, the apiKey is no longer a parameter of initPublisher. For now can you add an apiKey property to your publisher? eg.

```javascript
<ot-publisher apiKey="YOUR_APIKEY"></ot-publisher>
```

and let me know if that fixes it?

**Comment by dbounds** [comment]
@aullman, I'll test. How do you recommend passing the API key in JS instead of the markup?

**Comment by dbounds** [comment]
@aullman, that does not appear to address the issue, those different error now:

API Key is undefined. You must pass an API Key to initSession.(anonymous function) @ opentok.min.js:37
opentok.min.js:37 OT.exception :: title: Authentication error (1004) msg: API Key is undefined. You must pass an API Key to initSession.

**Comment by aullman** [comment]
What does your code look like @dbounds? Are you able to point me to the app so I can repro the issue? I'm not sure how you would be using these directives if you're passing the apiKey using JS? 

Sorry for the late response I have been busy travelling for work for the last 2 weeks.

**Comment by lommaj** [comment]
I have the same issue, using the example code from this library.

callling:
```
OTSession.init(apiKey, sessionId, token, function(err, session) {
          // Here you can do things to the OpenTok session
          // The err is bubbled up from session.connect
});
$scope.streams = OTSession.streams;
```
gives an error, I have apiKey also declared in a property on publisher as well.  still get same error.

```
API Key is undefined. You must pass an API Key to initSession.(anonymous function) @ TB.js:3397b.Session.g @ TB.js:22615
TB.js:3397 OT.exception :: title: Authentication error (1004) msg: API Key is undefined. You must pass an API Key to initSession.
```

**Comment by aullman** [comment]
Which version of opentok.js are you pointing to? I just tried demo.html and it's working fine for me pointing to the latest v2.5.1 at static.opentok.com/v2/js/opentok.min.js

**Comment by lommaj** [comment]
okay, i think the issue was updating bower dependencies.  

now i have opentok-angular, opentok-layout-js updated, opentok layout is trowing 

```
TypeError: angular.element(...).width is not a function
```

which of course is probably looking for the jquery .width() function.  however loading jquery before angular is keeping my entire app from loading :-( 

I guess I will just have to wrestle with this till I figure it out.

**Comment by lommaj** [comment]
Ah I figured it out, when adding jquery.. <div ui-view> breaks the page, it needs <div ui-view></div>

**Comment by lommaj** [comment]
okay, after all that im still getting the missing api key error.

I will look further.  I am updated to the following and have jquery now installed.
```
"opentok-layout-js": "~0.1.1",
 "opentok-angular": "~0.3.0"
```

**Comment by lommaj** [comment]
I have the correct static.opentok.com/v2/js/opentok.min.js dependency

**Comment by aullman** [comment]
Is the demo.html file working for you? Are you able to link me to your application so I can try to help debugging the issue?

**Comment by kesavard** [comment]
@aullman 
I am trying the same setup and ran into issue. It worked for me when I added API Key as property to publisher. However, I still called init in my js with apikey parameter. I am getting Authentication error

Interestingly, I have the demo.html working fine though I haven't passed the API key to publisher !

**Comment by aullman** [comment]
Hi @kesavard I'm not sure what the problem is. demo.html is working for you but your own app isn't? Are you getting a specific Authentication Error message?

**Comment by kesavard** [comment]
Hello @aullman, Here is the error. This goes away if I pass API key to init call. BTW, I dont see you passing the API key property to publisher in demo.html but the it works. Am I missing something

handle.js:103Invalid token format Token: "undefined". (1004)B @ handle.js:103
ot_error.js:354OT.exception :: title: Authentication error (1004) msg: Invalid token format Token: "undefined". (1004)u @ ot_error.js:354

**Comment by aullman** [comment]
Yeah, you need to include the apiKey in the OTSession.init call otherwise it thinks you didn't include a token which is the 3rd parameter. You don't have to pass the apiKey to the publisher if you have already called OTSession.init, only if you are using a publisher before you have initialised the Session.
