### ISSUE TITLE
Missing licensing information.

### ISSUE THREAD

**Issue by michplunkett** [aullman/OpenTok-Angular#13]
I noticed your Angular module for the whiteboard uses the MIT license, but this specific module does not have any licensing information. Is your intention to leave this license as the default one or an MIT open-source license?

**Comment by aullman** [comment]
Yes, sorry the MIT License was mentioned in package.json but I didn't include the LICENSE file. It's in there now.

**Comment by michplunkett** [comment]
Awesome, thanks!
