### ISSUE TITLE
Enable/Disable video and audio

### ISSUE THREAD

**Issue by jfsemaan** [aullman/OpenTok-Angular#15]
Hello,

How can I Enable/Disable video and audio in a ongoing call?

Thank you.

**Comment by aullman** [comment]
You use `subscriber.subscribeToVideo()` and `publisher.publishVideo()`. The documentation for these methods is at:
https://tokbox.com/developer/sdks/js/reference/Subscriber.html#subscribeToVideo
https://tokbox.com/developer/sdks/js/reference/Publisher.html#publishVideo

You can see me using it in opentok-meet (which uses this library) at:
https://github.com/aullman/opentok-meet/blob/master/public/js/controllers.js#L111
https://github.com/aullman/opentok-meet/blob/master/public/js/controllers.js#L217
