### ISSUE TITLE
OTSession keeps 'stale' connections

### ISSUE THREAD

**Issue by johnsolver** [aullman/OpenTok-Angular#17]
Perhaps it's due to how we use it, but it seems that connectionDestroyed which removes a connection is only called when someone disconnects.

However if you're the one closing the conversation the connection stays in the list of connections since OTSession is a 'service', so joining a new conversation you have that 'stale' connection that wasn't cleaned up left in the array. I had to manually clear the array of connection on init.

**Comment by aullman** [comment]
Good catch, yes it does not clean up the connections.
