### ISSUE TITLE
How can i set the name for a subscriber?

### ISSUE THREAD

**Issue by MetalCar** [aullman/OpenTok-Angular#20]
Hi,

can you told me, how I can set the name for a subscriber? Need this for a video-chat conference.
The conference members should know the name of the other members.

regards,
MetalCar

**Comment by aullman** [comment]
You actually set the name of the Publisher and that name carries through to all of the Subscribers to that Publisher. You can set the name of the publisher using eg:

```html
<ot-publisher props="{name: 'Adam'}"></ot-publisher>
```
