### ISSUE TITLE
npm published versions of OpenTok-Angular and opentok-layout-js incompatible

### ISSUE THREAD

**Issue by cwhenderson20** [aullman/OpenTok-Angular#29]
The versions of OpenTok-Angular and opentok-layout-js published to npm are incompatible with each other with regards to the `initLayoutContainer` API call. OT-Angular (0.4.2) expects the method to be attached to the global `TB` while OT-layout-js (0.3.1) only globally exposes it.

Maybe I'm missing something? But the only way I can get these two to work together is to modify OT-Angular's call to `initLayoutContainer` by removing the `TB` namespace — either that or to re-add the line in OT-layout-js that attached the method to the `OT` object:

```
OT.initLayoutContainer = exports.initLayoutContainer;
```

**Comment by AdiDahan** [comment]
Do you have example where to make this change ?

**Comment by cwhenderson20** [comment]
I modified the package to work for me [here](https://github.com/cwhenderson20/OpenTok-Angular/commit/b954149140c8557334a9c2b96ada957ba216571e). Does this help?

**Comment by AdiDahan** [comment]
Thanks, that worked.

**Comment by cwhenderson20** [comment]
I opened #30 to fix this issue if you wanted to take a look.
