### ISSUE TITLE
Use Big Elements with ot-layout directive

### ISSUE THREAD

**Issue by rhclayto** [aullman/OpenTok-Angular#31]
Hi,

I am able to use the 'OT_big' class on ot-publisher elements. However, is there any way to get the double-click resizing (dynamically adding & removing the class) effect seen in the opentok-layout-js demo using these directives? It seems that layout() has to be called to make it take effect, but how is layout() available to us using the directives?

Many thanks for your great work.

**Comment by aullman** [comment]
The directive is listening for the otLayout event and calling the layout method whenever that happens. So you just need to emit the otLayout event like so:

```javascript
$scope.$emit('otLayout');
```

[Here](https://github.com/aullman/opentok-meet/blob/ce64754ac0b96d67c05b25b623f9319da377f224/src/js/directives.js#L158) is an example of a directive which adds an expand button that does this.

**Comment by rhclayto** [comment]
Beautiful, thanks!
