### ISSUE TITLE
I saw message error at console in the chrome "opentok.min.js:57 OT.Publisher.onStreamAvailableError "

### ISSUE THREAD

**Issue by phanthinh** [aullman/OpenTok-Angular#33]
Hi 

I saw message error at console in the chrome "opentok.min.js:57 OT.Publisher.onStreamAvailableError "

Can you help me?

Regards,

**Comment by aullman** [comment]
That's a bug in the opentok SDK. I would contact TokBox Support https://support.tokbox.com/hc/en-us
