### ISSUE TITLE
Throwing [$rootScope:inprog] 

### ISSUE THREAD

**Issue by juampick** [aullman/OpenTok-Angular#36]
Hi! I have been using the library for several months without issues, I don't know what changed, but started throwing me some errors like:
`Error: [$rootScope:inprog] http://errors.angular.js.org/1.5.9.$rootScope/inprog?p0=NaNigest`
in this library I think so.

I'm using latest opentok-angular 1.2.1 version and angular 1.5.9 one.

Could you please give me a hand?

I appreciate your hard work here, thanks!

**Comment by aullman** [comment]
Which version are you using? There was a bug in v1.2.0 that was fixed in v1.2.1 that could cause this issue.

870a76ccf3b67cff77ddfb65fedf29bd363c4523

**Comment by juampick** [comment]
Using 1.2.1 version. 

Tested with `.js` working and with the minified `.min.js` didn't.. Any thoughts?

Thanks @aullman

**Comment by aullman** [comment]
Oh, perhaps I didn't update the minified version when I did the release.

**Comment by aullman** [comment]
yeah, that looks like the issue, sorry.

**Comment by juampick** [comment]
Thanks @aullman tested with `1.2.2` version and it's working! 👍
