### ISSUE TITLE
Pub'r and Sub'r with same token - $scope.streams is empty

### ISSUE THREAD

**Issue by steverob** [aullman/OpenTok-Angular#38]
First off thanks for this amazing project. 

If I want to use the `ot-subscriber` and `ot-publisher` directives in the same page using an `OTSession` created using the same `token`, I am not able to see the self-published stream in the streams list.

But if a different publisher starts streaming, that stream shows up in the list.

Is this something TokBox restricts? Thanks.

**Comment by aullman** [comment]
That's intentional so that you don't subscribe to yourself. If you want to get access to your own stream you can listen for the streamCreated event on the publisher.
