### ISSUE TITLE
Passing api key to publisher

### ISSUE THREAD

**Issue by slpn1** [aullman/OpenTok-Angular#42]
Hi,
In the publisher directive you are passing in the api key:

```
scope.publisher = OT.initPublisher(attrs.apikey || OTSession.session.apiKey,
            element[0], props, function(err) {
              if (err) {
                scope.$emit('otPublisherError', err, scope.publisher);
              }
            });
```

This does not match with the documentation here: [https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher](url)

Is there a reason for this? It seems to work both ways but want to know if either way has undesired side effects.

Thanks

**Comment by aullman** [comment]
The OpenTok API changed. It used to require an apiKey and it no longer does. It appears to be backwards compatible though.
