### ISSUE TITLE
opentok angular does not work with cordova

### ISSUE THREAD

**Issue by poeticninja** [aullman/OpenTok-Angular#5]
I am using the cordova opentok plugin (https://github.com/songz/cordova-plugin-opentok) with this angular opentok library and I am getting an error,

`Error: undefined is not an object (evaluating 'TB.$.eventing')`

Maybe this has something to do with this issue (or not :smile: ),

https://github.com/aullman/opentok-meet/issues/41

I am not used to the actual opentok library so I am not sure where to start looking. If you can point me in the right direction I dont mind trying to get this resolved.

**Comment by aullman** [comment]
Have you tried the cordova branch? https://github.com/aullman/OpenTok-Angular/tree/cordova

**Comment by frey1esm** [comment]
OK I grabbed that branch. Now it returns the following error:

`Error: undefined is not an object (evaluating '$document.context.addEventListener')
http://localhost:8100/lib/opentok-angular/opentok-angular.js:19:20`

**Comment by frey1esm** [comment]
Also, if I just run the demo code, it fails like this:

`TypeError: undefined is not a function (evaluating 'TB.updateViews()'), http://localhost:8100/lib/opentok-angular/opentok-angular.js, Line: 80`

**Comment by aullman** [comment]
Are you using the Cordova plugin?
https://github.com/songz/cordova-plugin-opentok

**Comment by aullman** [comment]
`updateViews()` is a method in the cordova version of opentok.js but not in the web version.

**Comment by edwardokim** [comment]
Hi,,
Im really new and have been having trouble integrating opentok for my ionic/cordova app that uses angular.

I have set up tb.js from '//static.opentok.com/webrtc/v2.2/js/TB.js' like how its done on https://github.com/aullman/OpenTok-Angular/blob/cordova/demo.html
which is giving me  'Cannot read property 'readyState' of undefined' error.

Also, I have made a file in my 'script' directory which I copied and pasted code from opentok-angular https://github.com/aullman/OpenTok-Angular/blob/cordova/opentok-angular.js and made it like a service which is giving me tonnes of error.. including TB is not defined etc etc
Could you be able to point me to right direction in getting video chat to work for my ionic cordova app/web app?

Thanks in advance

**Comment by edwardokim** [comment]
Hi,
So in order to make opentok Video chat to work on cordova App, I need to use it along side cordova Plugin right? (https://github.com/songz/cordova-plugin-opentok)

Im presuming, opentok.js from the cordova plugin above is like the TB.js from  https://github.com/aullman/OpenTok-Angular/tree/cordova?

I have got the angular-web opentok to work for my video call websites but im also trying to integrate it in to my cordova mobile app.

here are my steps if you can confirm that would be soooo helpful.

**Comment by azachar** [comment]
Any progress here?

**Comment by aullman** [comment]
@azachar are you trying to use the cordova-plugin-opentok project? I would recommend using https://github.com/aoberoi/cordova-plugin-opentokjs instead which should work just fine.

**Comment by azachar** [comment]
Thanks @aullman!

**Comment by azachar** [comment]
I did a small trick, i am using generator m-ionic and in the index.html i just added this
 ```
  <script src="opentok.js"></script> <!-- this will be 404 -->   
  <script src="//static.opentok.com/v2/js/opentok.js"></script> <!-- comment before publish to mobile device -->

    <script type="text/javascript">
        window.ionic.Platform.ready(function(){
            console.log('Device ready, starting angular');
            angular.bootstrap(document.body, ['yourAppName']);
        });
    </script>
```
and when your run gulp watch (it works in a browser), when you need to deploy it to a mobile it works too :)

**Comment by azachar** [comment]
Btw: cordova-plugin-opentokjs is not compilable  with the latest Xcode 7.2 so.. it really sucks..

**Comment by aullman** [comment]
@azachar have you reported that issue with @aoberoi?

**Comment by azachar** [comment]
Thanks for asking, not yet. I will do it now. Btw. I have patched your @aullman  libraries to be compatible with the official opentok cordova support. I am testing it.

**Comment by aullman** [comment]
Which one is the official one? TokBox don't have an official Cordova
library.

>

-- 

[image: TokBox] <http://www.tokbox.com>
Adam Ullman | Director API and Front-End Engineering
adam@tokbox.com
TokBox Inc - A Telefónica Company

**Comment by azachar** [comment]
It is based on this article: http://www.tokbox.com/blog/cordova-plugin-to-add-webrtc-audio-and-video/, so my changes i am testing again https://github.com/songz/cordova-plugin-opentok

**Comment by aullman** [comment]
Yeah, that article is 2 years old and Song no longer works at TokBox. The
recommended way to use Cordova now is the method @aoberoi uses. @aoberoi
still works at TokBox too :)

@aoberoi we should update the read me on Song's project to say this.



-- 

[image: TokBox] <http://www.tokbox.com>
Adam Ullman | Director API and Front-End Engineering
adam@tokbox.com
TokBox Inc - A Telefónica Company

**Comment by azachar** [comment]
Thanks for the info. I did not know that. It is very confusing what to use.

Btw I have updated your plugins in order to work with the old one plugin that is compilable with the latest Xcode. 

Feel free to look at my repo for modifications: 
https://github.com/aullman/OpenTok-Angular/compare/master...azachar:master
https://github.com/aullman/opentok-layout-js/compare/master...azachar:master
